// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MyToken$Type } from "./MyToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MyToken"]: MyToken$Type;
    ["contracts/MyToken.sol:MyToken"]: MyToken$Type;
  }

  interface ContractTypesMap {
    ["MyToken"]: GetContractReturnType<MyToken$Type["abi"]>;
    ["contracts/MyToken.sol:MyToken"]: GetContractReturnType<MyToken$Type["abi"]>;
  }
}
